name: CI - SupportTool (Docker Based)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin/docker-compose
          /usr/local/bin/docker-compose version

      - name: Run tests in Docker
        run: /usr/local/bin/docker-compose -f examples/supporttool/Docker-compose.yml up --build --abort-on-container-exit --exit-code-from supporttool
